apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: blue
  template:
    metadata:
      labels:
        deployment: blue
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: install
        image: busybox
        command:
        - wget
        - "-O"
        - "/work-dir/index.html"
        - https://raw.githubusercontent.com/jkhelil/openshift-blue-green-deployment/master/blue.html
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      dnsPolicy: Default
      volumes:
      - name: workdir
        emptydir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: blue-service
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    deployment: blue

  